services:
  django:
    image: "python3"
    volume:
      - "./app:/app"
    environment:
      DEBUG:
      SECRET_KEY:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
      DB_HOST:
      DB_PORT:
    ports:
      - ${PORT}:8000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "mariadb"
    volumes:
      - "mariadb_data:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  volumes:
    mariadb_data: