# Generated by Django 5.2.7 on 2025-10-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webnovel',
            name='cover_path',
        ),
        migrations.AddField(
            model_name='webnovel',
            name='cover',
            field=models.FileField(default='settings.MEDIA_ROOT/The eternal assassin.jpg', upload_to=''),
        ),
    ]
